"use client";
import {useCallback,useEffect,useState} from "react";
import {AlertTriangle,CheckCircle2,Clock3,RefreshCw,XCircle} from "lucide-react";
import {privateApiFetch} from "@/lib/private-client";
import styles from "./RuntimeOperations.module.css";
import {ConnectorCapabilities} from "./ConnectorCapabilities";
import {ConnectorWorkbench} from "./ConnectorWorkbench";
type SourceState="loading"|"online"|"error";
const when=(value?:string)=>value?new Intl.DateTimeFormat("de-DE",{dateStyle:"short",timeStyle:"short",timeZone:"Europe/Berlin"}).format(new Date(value)):"—";
function RuntimeOperationsEvidence({notify}:{notify:(message:string)=>void}){
 const [state,setState]=useState<SourceState>("loading"),[runs,setRuns]=useState<any[]>([]),[approvals,setApprovals]=useState<any[]>([]),[receipts,setReceipts]=useState<any[]>([]),[busy,setBusy]=useState("");
 const load=useCallback(async()=>{setState("loading");setRuns([]);setApprovals([]);setReceipts([]);try{const responses=await Promise.all([privateApiFetch("/api/agents/workflows",{cache:"no-store"}),privateApiFetch("/api/runtime/approvals",{cache:"no-store"}),privateApiFetch("/api/runtime/executions",{cache:"no-store"})]),bodies=await Promise.all(responses.map(response=>response.json()));if(responses.some(response=>!response.ok)||bodies.some(body=>!body.inventoryVerified))throw new Error();setRuns(bodies[0].runs||[]);setApprovals(bodies[1].approvals||[]);setReceipts(bodies[2].receipts||[]);setState("online")}catch{setState("error")}},[]);
 useEffect(()=>{load()},[load]);
 const reject=async(item:any)=>{setBusy(item.id);try{const response=await privateApiFetch("/api/runtime/approvals",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:"reject",id:item.id,version:item.version})}),body=await response.json();if(response.status===409){await load();throw new Error("Freigabe wurde bereits geändert; aktueller Stand geladen")}if(!response.ok)throw new Error(body.error||"Ablehnung fehlgeschlagen");await load();notify("Freigabe abgelehnt")}catch(error){notify(error instanceof Error?error.message:"Approval Ledger nicht erreichbar")}finally{setBusy("")}};
 return <section className={styles.surface}><div className="sectionhead"><div><h3>Runtime & Ausführungen</h3><span>Reale Runs, Freigaben und Receipts – ohne Aktivitäts-Simulation</span></div><button aria-label="Runtime neu laden" disabled={state==="loading"} onClick={load}><RefreshCw/></button></div>{state==="loading"&&<p role="status">Runtime Evidence wird geladen …</p>}{state==="error"&&<div className="honestEmpty"><AlertTriangle/><span><b>Runtime Evidence offline</b>Alte Zähler werden nicht als aktuell dargestellt.</span><button onClick={load}>Erneut prüfen</button></div>}{state==="online"&&<><div className={styles.summary}><span><b>{runs.length}</b>Runs</span><span><b>{approvals.filter(x=>x.status==="review_required").length}</b>offene Freigaben</span><span><b>{receipts.filter(x=>x.status==="unknown").length}</b>unklare Ausführungen</span></div><div className={styles.columns}><div><h4>Run-Verlauf</h4>{runs.length===0?<p>Keine echten Runs vorhanden.</p>:runs.slice(0,10).map(run=><details key={run.id}><summary><Clock3/><span><b>{run.workflowId}</b><small>{run.runtimeStatus||run.status} · {when(run.updatedAt)}</small></span></summary><dl><div><dt>Planner</dt><dd>{run.output?.runtime?.modelUsed?"model-assisted":"deterministic-local"}</dd></div><div><dt>Provider</dt><dd>{run.output?.provider||"lokale Regeln"}</dd></div><div><dt>Modell</dt><dd>{run.output?.model||"keines"}</dd></div><div><dt>Kosten</dt><dd>{run.output?.costEvidence?.estimatedCost??"nicht verfügbar"}</dd></div><div><dt>Context</dt><dd>{Object.keys(run.sourceEvidence||{}).length} Quellen</dd></div><div><dt>Steps</dt><dd>{run.steps?.length||0}</dd></div><div><dt>Invocations</dt><dd>{new Set((run.invocationEvents||[]).map((event:any)=>event.invocationId)).size}</dd></div><div><dt>Receipts</dt><dd>{run.receipts?.length||0}</dd></div></dl></details>)}</div><div><h4>Approval Center</h4>{approvals.length===0?<p>Keine offenen Freigaben.</p>:approvals.map(item=><article key={item.id}><b>{item.exactActionPreview?.title||item.actionType}</b><small>{item.riskClass} · {item.approvalClass} · läuft {when(item.expiresAt)} ab</small>{item.exactActionPreview?.start&&<small>{when(item.exactActionPreview.start)}–{when(item.exactActionPreview.end)}</small>}<code>{String(item.exactPayloadHash).slice(0,16)}…</code>{item.status==="review_required"?<><em>Genehmigung nur im exakten Ursprungsdialog; hier keine verkürzte Freigabe.</em><button disabled={busy===item.id} onClick={()=>reject(item)}><XCircle/>Ablehnen</button></>:<em>Abgelaufen – neue exakte Freigabe nötig</em>}</article>)}</div><div><h4>Execution History</h4>{receipts.length===0?<p>Noch keine Ausführungsbelege.</p>:receipts.slice(0,15).map(item=><article key={item.id}><span>{item.status==="confirmed"?<CheckCircle2/>:<AlertTriangle/>}<b>{item.actionType}</b></span><small>{item.external?"extern":"lokal"} · {item.retryPolicy} · {when(item.finishedAt||item.startedAt)}</small></article>)}</div><ConnectorCapabilities/></div></>}</section>
}
export function RuntimeOperations({notify}:{notify:(message:string)=>void}){return <><RuntimeOperationsEvidence notify={notify}/><ConnectorWorkbench notify={notify}/></>}
