import crypto from "node:crypto";import {operationalDatabase} from "../store/database.ts";import {decryptSensitive,encryptSensitive} from "../store/encryption.ts";import {addCalendarDays,berlinDateKey,berlinLocalIso} from "../weekly-planner.ts";
export type ScheduleDefinition={id:string;name:string;agentId:string;status:"active"|"paused";triggerType:"scheduled";cadence:"daily"|"weekly";hour:number;minute:number;dayOfWeek?:number;input:string;nextDueAt:string;lastRunAt?:string;version:number;createdAt:string;updatedAt:string};
const map=(row:Record<string,unknown>):ScheduleDefinition=>{const schedule=JSON.parse(String(row.schedule_json)),secret=decryptSensitive(String(row.input_enc)) as {input:string};return{id:String(row.id),name:String(row.name),agentId:String(row.agent_id),status:row.status as ScheduleDefinition["status"],triggerType:"scheduled",...schedule,input:secret.input,nextDueAt:String(row.next_due_at),lastRunAt:row.last_run_at?String(row.last_run_at):undefined,version:Number(row.version),createdAt:String(row.created_at),updatedAt:String(row.updated_at)}};
export function nextDue(input:{cadence:"daily"|"weekly";hour:number;minute:number;dayOfWeek?:number},from=new Date()){if(!Number.isInteger(input.hour)||input.hour<0||input.hour>23||!Number.isInteger(input.minute)||input.minute<0||input.minute>59)throw new Error("Zeitplan ist ungültig");if(input.cadence==="weekly"&&(!Number.isInteger(input.dayOfWeek)||input.dayOfWeek!<0||input.dayOfWeek!>6))throw new Error("Wochentag ist ungültig");let day=berlinDateKey(from);for(let offset=0;offset<9;offset+=1){if(offset)day=addCalendarDays(day,1);const weekday=new Date(`${day}T12:00:00Z`).getUTCDay();if(input.cadence==="weekly"&&weekday!==input.dayOfWeek)continue;const candidate=new Date(berlinLocalIso(day,input.hour,input.minute));if(candidate>from)return candidate.toISOString()}throw new Error("Nächster Zeitpunkt konnte nicht bestimmt werden")}
export function createSchedule(input:{name:string;agentId:string;cadence:"daily"|"weekly";hour:number;minute:number;dayOfWeek?:number;input:string}){const name=String(input.name||"").trim(),text=String(input.input||"").trim();if(name.length<2||name.length>80||text.length<2||text.length>1000)throw new Error("Zeitplan ist ungültig");const id=crypto.randomUUID(),now=new Date().toISOString(),due=nextDue(input,new Date());operationalDatabase().prepare("INSERT INTO runtime_schedules(id,name,agent_id,status,trigger_type,schedule_json,input_enc,next_due_at,version,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,1,?,?)").run(id,name,input.agentId,"active","scheduled",JSON.stringify({cadence:input.cadence,hour:input.hour,minute:input.minute,dayOfWeek:input.dayOfWeek}),encryptSensitive({input:text}),due,now,now);return getSchedule(id)!}
export function getSchedule(id:string){const row=operationalDatabase().prepare("SELECT * FROM runtime_schedules WHERE id=?").get(id) as Record<string,unknown>|undefined;return row?map(row):null}
export function listSchedules(limit=50){return(operationalDatabase().prepare("SELECT * FROM runtime_schedules ORDER BY updated_at DESC LIMIT ?").all(Math.min(50,Math.max(1,Math.trunc(limit)||50))) as Array<Record<string,unknown>>).map(map)}
export function listDueSchedules(now=new Date(),limit=10){return(operationalDatabase().prepare("SELECT * FROM runtime_schedules WHERE status='active' AND next_due_at<=? ORDER BY next_due_at LIMIT ?").all(now.toISOString(),Math.min(10,Math.max(1,limit))) as Array<Record<string,unknown>>).map(map)}
export function markScheduleRun(id:string,expectedVersion:number,at=new Date()){const current=getSchedule(id);if(!current||current.version!==expectedVersion)throw new Error("Datenkonflikt: Zeitplan wurde geändert");const next=nextDue(current,at),now=at.toISOString(),result=operationalDatabase().prepare("UPDATE runtime_schedules SET last_run_at=?,next_due_at=?,version=version+1,updated_at=? WHERE id=? AND version=?").run(now,next,now,id,expectedVersion);if(!result.changes)throw new Error("Datenkonflikt: Zeitplan wurde geändert");return getSchedule(id)!}
