import assert from "node:assert/strict";import {spawnSync} from "node:child_process";import {mkdtempSync,rmSync} from "node:fs";import os from "node:os";import path from "node:path";import test from "node:test";import {pathToFileURL} from "node:url";
test("local mutation tools are narrow, versioned, receipted and require direct intent",()=>{const root=mkdtempSync(path.join(os.tmpdir(),"agentic-os-local-tools-")),serviceUrl=pathToFileURL(path.resolve("lib/runtime/tools/local-mutation-service.ts")).href,storeUrl=pathToFileURL(path.resolve("lib/shared-store.ts")).href;const script=`
await import(${JSON.stringify(storeUrl)});const {executeLocalMutationTool}=await import(${JSON.stringify(serviceUrl)});
try{executeLocalMutationTool({toolId:"task.create",payload:{title:"Denied task"},authority:"agent_proposal"});throw new Error("agent proposal executed")}catch(error){if(!String(error.message).includes("Review"))throw error}
const created=executeLocalMutationTool({toolId:"task.create",payload:{title:"Exact local task",area:"Inbox",priority:"high"},authority:"user_direct_intent"});if(created.externalActionsPerformed||created.receipt.status!=="confirmed")throw new Error("missing receipt");
try{executeLocalMutationTool({toolId:"task.complete",payload:{id:created.result.id,version:99},authority:"user_direct_intent"});throw new Error("stale version accepted")}catch(error){if(!String(error.message).includes("Datenkonflikt"))throw error}
const done=executeLocalMutationTool({toolId:"task.complete",payload:{id:created.result.id,version:created.result.version},authority:"user_direct_intent"});if(!done.result.done||done.result.status!=="completed")throw new Error("task not completed");
try{executeLocalMutationTool({toolId:"generic_record_mutation",payload:{},authority:"user_direct_intent"});throw new Error("generic tool accepted")}catch(error){if(!String(error.message).includes("Unbekanntes"))throw error}
`;try{const result=spawnSync(process.execPath,["--input-type=module","--eval",script],{cwd:root,encoding:"utf8",env:{...process.env,AUTH_SECRET:"local-tool-test-secret"}});assert.equal(result.status,0,result.stderr||result.stdout)}finally{rmSync(root,{recursive:true,force:true})}});
test("local action API preserves private mutation boundaries",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile(new URL("../app/api/runtime/local-actions/route.ts",import.meta.url),"utf8"));for(const contract of ["verifyLocalSession","trustedPrivateMutationOrigin","readPrivateJson","no-store, private","user_direct_intent"])assert.match(source,new RegExp(contract));assert.doesNotMatch(source,/generic_record_mutation|tableName|arbitrary/i)});
