import type { AgentDefinition, PlannerResult } from "../types.ts";
import { validatePlannerResult } from "../planning/validation.ts";

const object=(value:unknown):Record<string,unknown>=>{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("Strukturierter Planner-Output ist ungültig");return value as Record<string,unknown>};
const text=(value:unknown,max:number)=>{const result=String(value||"").trim();if(!result||result.length>max)throw new Error("Strukturierter Planner-Text ist ungültig");return result};
export function parseStructuredPlannerOutput(agent:AgentDefinition,value:unknown,evidence:PlannerResult["evidence"]):PlannerResult{
 const raw=object(value),skills=(Array.isArray(raw.skillInvocations)?raw.skillInvocations:[]).map(item=>{const entry=object(item);return{skillId:text(entry.skillId,80),input:object(entry.input||{}),requestedBy:"planner" as const}}),tools=(Array.isArray(raw.toolIntents)?raw.toolIntents:[]).map(item=>{const entry=object(item);return{toolId:text(entry.toolId,80),input:object(entry.input||{}),requestedBySkillId:entry.requestedBySkillId?text(entry.requestedBySkillId,80):undefined}}),actions=(Array.isArray(raw.proposedActions)?raw.proposedActions:[]).map((item,index)=>{const entry=object(item);return{id:String(entry.id||`model-${index+1}`).slice(0,80),title:text(entry.title,160),rationale:text(entry.rationale,500),type:"proposal" as const,externalAction:false as const,requiresSeparateApproval:true as const}}),memories=(Array.isArray(raw.memoryCandidateSuggestions)?raw.memoryCandidateSuggestions:[]).map(item=>{const entry=object(item),kind=text(entry.kind,20),scope=text(entry.scope,20);if(!["policy","preference","fact","observation","summary"].includes(kind)||!["global","agent","project","area"].includes(scope))throw new Error("Memory-Vorschlag ist ungültig");return{kind:kind as PlannerResult["memorySuggestions"][number]["kind"],scope:scope as PlannerResult["memorySuggestions"][number]["scope"],reason:text(entry.reason,300)}});
 return validatePlannerResult(agent,{summary:text(raw.summary,1000),proposedSteps:actions,requiresApproval:actions.length>0,modelUsed:false,externalActionsPerformed:false,evidence,skillInvocations:skills,toolIntents:tools,memorySuggestions:memories,approvalRequirements:[]});
}
