import crypto from "node:crypto";import {googleRequestSignal} from "./google-transport.ts";import {ModelFailure} from "./runtime/models/types.ts";
export const googleTasksScopes={read:"https://www.googleapis.com/auth/tasks.readonly",write:"https://www.googleapis.com/auth/tasks"} as const;
type Transport=(url:string,init:RequestInit)=>Promise<Response>;const base="https://tasks.googleapis.com/tasks/v1";
const id=(value:unknown,label:string)=>{const text=String(value||"");if(!/^[A-Za-z0-9_-]{1,256}$/.test(text))throw new Error(`${label} ist ungültig`);return text};const title=(value:unknown)=>{const text=String(value||"").trim();if(!text||text.length>1024)throw new Error("Task-Titel ist ungültig");return text};
function requireScope(scopes:readonly string[],write=false){if(!scopes.includes(googleTasksScopes.write)&&!( !write&&scopes.includes(googleTasksScopes.read)))throw new ModelFailure("policy_blocked","Google Tasks OAuth Scope fehlt")}
async function request(transport:Transport,url:string,init:RequestInit){const response=await transport(url,{...init,cache:"no-store",signal:init.signal||googleRequestSignal()});if(response.status===404)return{response,body:null};if(!response.ok)throw new Error(response.status===409||response.status===412?"Remote State Konflikt":"Google Tasks Anfrage fehlgeschlagen");return{response,body:response.status===204?null:await response.json()}}
export function createGoogleTasksConnector(input:{accessToken:string;scopes:readonly string[];allowedTaskListIds?:readonly string[];transport?:Transport}){const transport=input.transport||fetch,headers={authorization:`Bearer ${input.accessToken}`,"content-type":"application/json"};const list=(value:string)=>{const result=id(value,"Task-Liste");if(input.allowedTaskListIds?.length&&!input.allowedTaskListIds.includes(result))throw new Error("Task-Liste ist nicht ausgewählt");return result};return{
 assertCapability(write=false){requireScope(input.scopes,write);return true},
 async listTaskLists(limit=20){requireScope(input.scopes);const max=Math.min(50,Math.max(1,Math.trunc(limit)));const {body}=await request(transport,`${base}/users/@me/lists?maxResults=${max}`,{headers});return Array.isArray(body?.items)?body.items.slice(0,max):[]},
 async listTasks(taskListId:string,options:{limit?:number;showCompleted?:boolean}={}){requireScope(input.scopes);const max=Math.min(50,Math.max(1,Math.trunc(options.limit||20))),query=new URLSearchParams({maxResults:String(max),showCompleted:String(Boolean(options.showCompleted)),showHidden:"false"});const {body}=await request(transport,`${base}/lists/${encodeURIComponent(list(taskListId))}/tasks?${query}`,{headers});return Array.isArray(body?.items)?body.items.slice(0,max):[]},
 async getTask(taskListId:string,taskId:string){requireScope(input.scopes);return(await request(transport,`${base}/lists/${encodeURIComponent(list(taskListId))}/tasks/${encodeURIComponent(id(taskId,"Task"))}`,{headers})).body},
 async createTask(taskListId:string,payload:{title:string;notes?:string;due?:string}){requireScope(input.scopes,true);const body={title:title(payload.title),notes:String(payload.notes||"").slice(0,4000)||undefined,due:payload.due};return(await request(transport,`${base}/lists/${encodeURIComponent(list(taskListId))}/tasks`,{method:"POST",headers,body:JSON.stringify(body)})).body},
 async updateTask(taskListId:string,taskId:string,payload:Record<string,unknown>,expectedEtag:string){requireScope(input.scopes,true);if(!expectedEtag)throw new Error("Remote Version fehlt");const current=await this.getTask(taskListId,taskId);if(!current||current.etag!==expectedEtag)throw new Error("Remote State Konflikt");const body={title:payload.title?title(payload.title):current.title,notes:payload.notes===undefined?current.notes:String(payload.notes).slice(0,4000),due:payload.due===undefined?current.due:payload.due,status:payload.status===undefined?current.status:payload.status};return(await request(transport,`${base}/lists/${encodeURIComponent(list(taskListId))}/tasks/${encodeURIComponent(id(taskId,"Task"))}`,{method:"PATCH",headers:{...headers,"if-match":expectedEtag},body:JSON.stringify(body)})).body},
 async deleteTask(taskListId:string,taskId:string,expectedEtag:string){requireScope(input.scopes,true);if(!expectedEtag)throw new Error("Remote Version fehlt");const current=await this.getTask(taskListId,taskId);if(!current||current.etag!==expectedEtag)throw new Error("Remote State Konflikt");await request(transport,`${base}/lists/${encodeURIComponent(list(taskListId))}/tasks/${encodeURIComponent(id(taskId,"Task"))}`,{method:"DELETE",headers:{...headers,"if-match":expectedEtag}});const check=await request(transport,`${base}/lists/${encodeURIComponent(list(taskListId))}/tasks/${encodeURIComponent(id(taskId,"Task"))}`,{headers});return{confirmed:check.response.status===404,verificationId:crypto.createHash("sha256").update(`${taskListId}:${taskId}`).digest("hex").slice(0,16)}}
}}
