import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { DatabaseSync } from 'node:sqlite';

export const operationalKinds=['projects','tasks','habits','journal_metadata','inbox_items','agents','skills','area_records','weekly_plans','weekly_outcomes','focus_proposals','approvals','progress_items','audit_log'] as const;
export type OperationalKind=typeof operationalKinds[number];
const stateDir=()=>path.join(process.cwd(),'local-state');
const dbPath=()=>path.join(stateDir(),'agentic-os.sqlite');
let database:DatabaseSync|null=null;

const migrations=[{version:1,sql:`
CREATE TABLE IF NOT EXISTS schema_migrations(version INTEGER PRIMARY KEY,applied_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS projects(id TEXT PRIMARY KEY,title TEXT NOT NULL,status TEXT NOT NULL,data_json TEXT NOT NULL,sensitive_enc TEXT,version INTEGER NOT NULL DEFAULT 1,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS tasks(id TEXT PRIMARY KEY,project_id TEXT,title TEXT NOT NULL,status TEXT NOT NULL,due_at TEXT,data_json TEXT NOT NULL,sensitive_enc TEXT,version INTEGER NOT NULL DEFAULT 1,updated_at TEXT NOT NULL,FOREIGN KEY(project_id) REFERENCES projects(id));
CREATE TABLE IF NOT EXISTS habits(id TEXT PRIMARY KEY,title TEXT NOT NULL,cadence TEXT NOT NULL,data_json TEXT NOT NULL,sensitive_enc TEXT,version INTEGER NOT NULL DEFAULT 1,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS journal_metadata(id TEXT PRIMARY KEY,entry_date TEXT NOT NULL,mood TEXT,energy INTEGER,data_json TEXT NOT NULL,sensitive_enc TEXT,version INTEGER NOT NULL DEFAULT 1,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS inbox_items(id TEXT PRIMARY KEY,item_type TEXT NOT NULL,status TEXT NOT NULL,data_json TEXT NOT NULL,sensitive_enc TEXT,version INTEGER NOT NULL DEFAULT 1,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS agents(id TEXT PRIMARY KEY,name TEXT NOT NULL,status TEXT NOT NULL,config_json TEXT NOT NULL,sensitive_enc TEXT,version INTEGER NOT NULL DEFAULT 1,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS skills(id TEXT PRIMARY KEY,name TEXT NOT NULL,status TEXT NOT NULL,config_json TEXT NOT NULL,version INTEGER NOT NULL DEFAULT 1,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS approvals(id TEXT PRIMARY KEY,action_type TEXT NOT NULL,status TEXT NOT NULL,exact_diff_json TEXT NOT NULL,expires_at TEXT NOT NULL,decided_at TEXT,version INTEGER NOT NULL DEFAULT 1,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS progress_items(id TEXT PRIMARY KEY,phase TEXT NOT NULL,status TEXT NOT NULL,evidence_json TEXT NOT NULL,version INTEGER NOT NULL DEFAULT 1,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS audit_log(id TEXT PRIMARY KEY,action TEXT NOT NULL,entity_type TEXT,entity_id TEXT,metadata_json TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS migration_previews(id TEXT PRIMARY KEY,device_id TEXT NOT NULL,payload_hash TEXT NOT NULL,keys_json TEXT NOT NULL,conflict_count INTEGER NOT NULL,status TEXT NOT NULL,created_at TEXT NOT NULL);`},{version:2,sql:`ALTER TABLE habits ADD COLUMN status TEXT NOT NULL DEFAULT 'active';ALTER TABLE journal_metadata ADD COLUMN status TEXT NOT NULL DEFAULT 'active';`},{version:3,sql:`CREATE TABLE IF NOT EXISTS area_records(id TEXT PRIMARY KEY,area TEXT NOT NULL,record_type TEXT NOT NULL,title TEXT NOT NULL,status TEXT NOT NULL,data_json TEXT NOT NULL,sensitive_enc TEXT NOT NULL,version INTEGER NOT NULL DEFAULT 1,updated_at TEXT NOT NULL);CREATE INDEX IF NOT EXISTS area_records_area_type_idx ON area_records(area,record_type,status);`},{version:4,sql:`CREATE TABLE IF NOT EXISTS weekly_plans(id TEXT PRIMARY KEY,week_start TEXT NOT NULL,status TEXT NOT NULL,plan_enc TEXT NOT NULL,version INTEGER NOT NULL DEFAULT 1,updated_at TEXT NOT NULL);CREATE INDEX IF NOT EXISTS weekly_plans_week_idx ON weekly_plans(week_start,updated_at);`},{version:5,sql:`CREATE TABLE IF NOT EXISTS weekly_outcomes(id TEXT PRIMARY KEY,plan_id TEXT NOT NULL,source_kind TEXT NOT NULL,source_id TEXT,rank INTEGER NOT NULL,status TEXT NOT NULL,title_enc TEXT NOT NULL,version INTEGER NOT NULL DEFAULT 1,updated_at TEXT NOT NULL,FOREIGN KEY(plan_id) REFERENCES weekly_plans(id));CREATE TABLE IF NOT EXISTS focus_proposals(id TEXT PRIMARY KEY,plan_id TEXT NOT NULL,outcome_id TEXT NOT NULL,target_calendar_id TEXT NOT NULL,start_at TEXT NOT NULL,end_at TEXT NOT NULL,timezone TEXT NOT NULL,status TEXT NOT NULL,proposal_enc TEXT NOT NULL,approval_ref TEXT,audit_ref TEXT,version INTEGER NOT NULL DEFAULT 1,updated_at TEXT NOT NULL,FOREIGN KEY(plan_id) REFERENCES weekly_plans(id),FOREIGN KEY(outcome_id) REFERENCES weekly_outcomes(id));CREATE INDEX IF NOT EXISTS weekly_outcomes_plan_idx ON weekly_outcomes(plan_id,rank);CREATE INDEX IF NOT EXISTS focus_proposals_plan_idx ON focus_proposals(plan_id,start_at);`}];

function db(){if(database)return database;fs.mkdirSync(stateDir(),{recursive:true});database=new DatabaseSync(dbPath());database.exec('PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000; CREATE TABLE IF NOT EXISTS schema_migrations(version INTEGER PRIMARY KEY,applied_at TEXT NOT NULL);');const applied=new Set((database.prepare('SELECT version FROM schema_migrations').all() as Array<{version:number}>).map(row=>row.version));for(const migration of migrations){if(applied.has(migration.version))continue;database.exec('BEGIN IMMEDIATE');try{database.exec(migration.sql);database.prepare('INSERT INTO schema_migrations(version,applied_at) VALUES(?,?)').run(migration.version,new Date().toISOString());database.exec('COMMIT')}catch(error){database.exec('ROLLBACK');throw error}}return database}
function fieldKey(){const secret=process.env.AUTH_SECRET;if(!secret)throw new Error('AUTH_SECRET fehlt');return crypto.createHash('sha256').update(`agentic-os-sensitive-fields:${secret}`).digest()}
export function encryptSensitive(value:unknown){const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',fieldKey(),iv),encrypted=Buffer.concat([cipher.update(JSON.stringify(value),'utf8'),cipher.final()]);return[iv.toString('base64url'),cipher.getAuthTag().toString('base64url'),encrypted.toString('base64url')].join('.')}
export function decryptSensitive(value:string){const[iv,tag,data]=value.split('.'),decipher=crypto.createDecipheriv('aes-256-gcm',fieldKey(),Buffer.from(iv,'base64url'));decipher.setAuthTag(Buffer.from(tag,'base64url'));return JSON.parse(Buffer.concat([decipher.update(Buffer.from(data,'base64url')),decipher.final()]).toString('utf8'))}
export function storeStatus(){const counts=Object.fromEntries(operationalKinds.map(table=>[table,Number((db().prepare(`SELECT COUNT(*) AS count FROM ${table}`).get() as {count:number}).count)]));const version=(db().prepare('SELECT MAX(version) AS version FROM schema_migrations').get() as {version:number}).version;return{online:true,engine:'node:sqlite',schemaVersion:version,counts,localOnly:true,wal:true,conflictGate:true,sensitiveFieldEncryption:'AES-256-GCM'}}
export function createMigrationPreview(deviceId:string,keys:string[]){const normalized=[...new Set(keys.filter(key=>/^aos:(tasks|journal|brand|inbox)$/.test(key)))].sort();const mapping:Record<string,OperationalKind>={'aos:tasks':'tasks','aos:journal':'journal_metadata','aos:brand':'progress_items','aos:inbox':'inbox_items'};const conflicts=normalized.filter(key=>Number((db().prepare(`SELECT COUNT(*) AS count FROM ${mapping[key]}`).get() as {count:number}).count)>0).length;const id=crypto.randomUUID(),createdAt=new Date().toISOString(),hash=crypto.createHash('sha256').update(JSON.stringify(normalized)).digest('hex');db().prepare('INSERT INTO migration_previews(id,device_id,payload_hash,keys_json,conflict_count,status,created_at) VALUES(?,?,?,?,?,?,?)').run(id,deviceId,hash,JSON.stringify(normalized),conflicts,'review_required',createdAt);return{id,deviceId,discoveredKeys:normalized,conflictCount:conflicts,status:'review_required',writesPerformed:false,createdAt}}
const crudKinds=['projects','tasks','habits','journal_metadata','inbox_items','agents','skills','area_records'] as const;export type CrudKind=typeof crudKinds[number];
export function isCrudKind(value:string):value is CrudKind{return(crudKinds as readonly string[]).includes(value)}
const areaTypes:Record<string,readonly string[]>={faith:['practice','quran','dua','reflection'],health:['training','nutrition','recovery','measurement'],finance:['account','income','expense','budget','goal','recurring'],relations:['person','contact','birthday','follow_up','note'],career:['goal','task','learning','opportunity','milestone','document']};
export function validateRecord(kind:CrudKind,input:any){const title=String(input?.title||input?.name||'').trim();if(title.length<2||title.length>120)throw new Error('Name muss 2–120 Zeichen haben');const status=String(input?.status||'active');if(!['active','planned','paused','archived','metadata_only'].includes(status))throw new Error('Ungültiger Status');if(kind==='area_records'){const area=String(input?.area||''),recordType=String(input?.recordType||'');if(!areaTypes[area]?.includes(recordType))throw new Error('Ungültiger Bereich oder Eintragstyp');const details=String(input?.details||'');if(details.length>4000)throw new Error('Details dürfen höchstens 4000 Zeichen haben');const track=String(input?.track||'');if(area==='career'&&!['employee','business'].includes(track))throw new Error('Karrierepfad fehlt');if(area!=='career'&&track)throw new Error('Karrierepfad nur für Karriere erlaubt');}return{...input,title,name:title,status}}
function areaRecordPayload(data:any,id:string){const{area,recordType,title,status}=data;const sensitive={details:String(data.details||''),date:String(data.date||''),amount:String(data.amount||''),currency:String(data.currency||'EUR'),track:String(data.track||'')};return{publicData:JSON.stringify({id,area,recordType,title,name:title,status}),sensitive:encryptSensitive(sensitive)}}
export function listRecords(kind:CrudKind){const rows=db().prepare(`SELECT * FROM ${kind} WHERE status <> 'archived' ORDER BY updated_at DESC`).all() as Array<Record<string,any>>;return rows.map(row=>{const visible=JSON.parse(String(row.data_json||row.config_json||'{}'));const sensitive=kind==='area_records'&&row.sensitive_enc?decryptSensitive(String(row.sensitive_enc)):{};return{id:row.id,version:row.version,updatedAt:row.updated_at,...visible,...sensitive}})}
export function createRecord(kind:CrudKind,input:any){const data=validateRecord(kind,input),id=crypto.randomUUID(),now=new Date().toISOString(),storedData=kind==='skills'?{...data,status:'metadata_only'}:data,payload=JSON.stringify({...storedData,id});if(kind==='projects')db().prepare('INSERT INTO projects(id,title,status,data_json,updated_at) VALUES(?,?,?,?,?)').run(id,data.title,data.status,payload,now);else if(kind==='tasks')db().prepare('INSERT INTO tasks(id,project_id,title,status,due_at,data_json,updated_at) VALUES(?,?,?,?,?,?,?)').run(id,data.projectId||null,data.title,data.status,data.dueAt||null,payload,now);else if(kind==='habits')db().prepare('INSERT INTO habits(id,title,cadence,status,data_json,updated_at) VALUES(?,?,?,?,?,?)').run(id,data.title,data.cadence||'daily',data.status,payload,now);else if(kind==='journal_metadata')db().prepare('INSERT INTO journal_metadata(id,entry_date,mood,energy,status,data_json,sensitive_enc,updated_at) VALUES(?,?,?,?,?,?,?,?)').run(id,data.entryDate||now.slice(0,10),data.mood||null,data.energy||null,data.status,payload,data.text?encryptSensitive({text:data.text}):null,now);else if(kind==='inbox_items')db().prepare('INSERT INTO inbox_items(id,item_type,status,data_json,updated_at) VALUES(?,?,?,?,?)').run(id,data.itemType||'note',data.status,payload,now);else if(kind==='agents')db().prepare('INSERT INTO agents(id,name,status,config_json,updated_at) VALUES(?,?,?,?,?)').run(id,data.name,data.status,payload,now);else if(kind==='area_records'){const secured=areaRecordPayload(data,id);db().prepare('INSERT INTO area_records(id,area,record_type,title,status,data_json,sensitive_enc,updated_at) VALUES(?,?,?,?,?,?,?,?)').run(id,data.area,data.recordType,data.title,data.status,secured.publicData,secured.sensitive,now)}else db().prepare('INSERT INTO skills(id,name,status,config_json,updated_at) VALUES(?,?,?,?,?)').run(id,data.name,'metadata_only',payload,now);db().prepare('INSERT INTO audit_log(id,action,entity_type,entity_id,metadata_json,created_at) VALUES(?,?,?,?,?,?)').run(crypto.randomUUID(),'create',kind,id,JSON.stringify({source:'agentic-os-ui'}),now);return{id,...storedData,text:undefined,version:1,updatedAt:now}}
export function updateRecord(kind:CrudKind,id:string,input:any){const current=listRecords(kind).find(record=>record.id===id);if(!current)throw new Error('Eintrag nicht gefunden');const data=validateRecord(kind,{...current,...input}),now=new Date().toISOString(),payload=JSON.stringify({...data,id});let result;if(kind==='area_records'){const secured=areaRecordPayload(data,id);result=db().prepare('UPDATE area_records SET area=?,record_type=?,title=?,data_json=?,sensitive_enc=?,status=?,version=version+1,updated_at=? WHERE id=?').run(data.area,data.recordType,data.title,secured.publicData,secured.sensitive,data.status,now,id)}else{const column=kind==='agents'||kind==='skills'?'config_json':'data_json';result=db().prepare(`UPDATE ${kind} SET ${column}=?,status=?,version=version+1,updated_at=? WHERE id=?`).run(payload,data.status,now,id)}if(!result.changes)throw new Error('Eintrag nicht aktualisiert');db().prepare('INSERT INTO audit_log(id,action,entity_type,entity_id,metadata_json,created_at) VALUES(?,?,?,?,?,?)').run(crypto.randomUUID(),'update',kind,id,JSON.stringify({source:'agentic-os-ui'}),now);return{id,...data,version:Number(current.version)+1,updatedAt:now}}
export function archiveRecord(kind:CrudKind,id:string){const now=new Date().toISOString(),result=db().prepare(`UPDATE ${kind} SET status='archived',version=version+1,updated_at=? WHERE id=?`).run(now,id);if(!result.changes)throw new Error('Eintrag nicht gefunden');db().prepare('INSERT INTO audit_log(id,action,entity_type,entity_id,metadata_json,created_at) VALUES(?,?,?,?,?,?)').run(crypto.randomUUID(),'archive',kind,id,'{}',now);return{archived:true,id}}
export function validateWeeklyPlan(input:any){
  if(input?.timezone!=='Europe/Berlin')throw new Error('Wochenplan-Zeitzone muss Europe/Berlin sein');
  if(!Array.isArray(input?.outcomes)||input.outcomes.length>3)throw new Error('Wochenplan darf höchstens 3 Outcomes enthalten');
  if(!Array.isArray(input?.blocks)||input.blocks.length>3)throw new Error('Wochenplan darf höchstens 3 Fokusvorschläge enthalten');
  const outcomeIds=input.outcomes.map((item:any)=>String(item.id||''));
  if(outcomeIds.some((id:string)=>!id)||new Set(outcomeIds).size!==outcomeIds.length)throw new Error('Outcome-IDs müssen eindeutig sein');
  const buffer=Number(input?.capacity?.bufferPercent);
  if(!Number.isFinite(buffer)||buffer<30||buffer>40)throw new Error('Puffer muss 30–40 Prozent betragen');
  if(input?.backgroundWrites!==false||input?.writesPerformed!==false)throw new Error('Hintergrundwrites sind verboten');
  const windowStart=Date.parse(input?.constraints?.windowStart),windowEnd=Date.parse(input?.constraints?.windowEnd);
  if(!Number.isFinite(windowStart)||!Number.isFinite(windowEnd)||windowEnd<=windowStart)throw new Error('8-Tage-Fenster ungültig');
  const blockIds=new Set<string>(),trainingDays=new Set((input?.constraints?.trainingDays||[]).map(String)),selectedCalendars=new Set((input?.constraints?.selectedCalendarIds||[]).map(String));
  const busyIntervals=(input?.constraints?.busyIntervals||[]).map((item:any)=>({start:Date.parse(item.start),end:Date.parse(item.end)})).filter((item:any)=>Number.isFinite(item.start)&&Number.isFinite(item.end)&&item.end>item.start);
  const accepted:Array<{start:number;end:number}>=[];
  const berlinDay=(instant:number)=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Berlin',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(instant));
  for(const block of input.blocks){
    if(!block.id||blockIds.has(block.id))throw new Error('Fokusblock-IDs müssen eindeutig sein');blockIds.add(block.id);
    if(!outcomeIds.includes(String(block.outcomeId)))throw new Error('Fokusblock verweist auf ein fremdes Outcome');
    if(block.status!=='proposal'||block.writesPerformed!==false)throw new Error('Fokusblock muss ein ungeschriebener Vorschlag sein');
    if(block.timezone!=='Europe/Berlin')throw new Error('Fokusblock-Zeitzone ungültig');
    if(!selectedCalendars.has(String(block.calendarId)))throw new Error('Fokusblock verwendet einen nicht ausgewählten Kalender');
    const start=Date.parse(block.start),end=Date.parse(block.end);
    if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start)throw new Error('Fokusblock-Zeitfenster ungültig');
    if(start<windowStart||end>windowEnd)throw new Error('Fokusblock liegt außerhalb des 8-Tage-Fensters');
    if(trainingDays.has(berlinDay(start)))throw new Error('Fokusblock liegt auf einem Trainingstag');
    if(busyIntervals.some((item:any)=>start<item.end&&end>item.start))throw new Error('Fokusblock überschneidet einen Kalendertermin');
    if(accepted.some(item=>start<item.end&&end>item.start))throw new Error('Fokusblöcke überschneiden sich');
    accepted.push({start,end});
  }
  return input;
}
export function saveWeeklyPlan(input:any){const exact=validateWeeklyPlan(input),id=crypto.randomUUID(),now=new Date().toISOString(),status='proposal',plan={...exact,id,status,decisions:{selectedOutcomeIds:[],selectedBlockIds:[],reviewed:false},createdAt:now,updatedAt:now},database=db();database.exec('BEGIN IMMEDIATE');try{database.prepare('INSERT INTO weekly_plans(id,week_start,status,plan_enc,updated_at) VALUES(?,?,?,?,?)').run(id,String(plan.weekStart),status,encryptSensitive(plan),now);for(const[outcomeRank,outcome]of plan.outcomes.entries())database.prepare('INSERT INTO weekly_outcomes(id,plan_id,source_kind,source_id,rank,status,title_enc,updated_at) VALUES(?,?,?,?,?,?,?,?)').run(outcome.id,id,outcome.sourceKind,outcome.sourceId||null,outcomeRank+1,'proposal',encryptSensitive({title:outcome.title,area:outcome.area||'',reason:outcome.reason||''}),now);for(const block of plan.blocks)database.prepare('INSERT INTO focus_proposals(id,plan_id,outcome_id,target_calendar_id,start_at,end_at,timezone,status,proposal_enc,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run(block.id,id,block.outcomeId,block.calendarId,block.start,block.end,block.timezone,'proposal',encryptSensitive({title:block.title,calendarName:block.calendarName||''}),now);database.prepare('INSERT INTO audit_log(id,action,entity_type,entity_id,metadata_json,created_at) VALUES(?,?,?,?,?,?)').run(crypto.randomUUID(),'weekly_plan.generate','weekly_plan',id,JSON.stringify({outcomeCount:plan.outcomes.length,blockCount:plan.blocks.length,bufferPercent:plan.capacity.bufferPercent,writesPerformed:false}),now);database.exec('COMMIT')}catch(error){database.exec('ROLLBACK');throw error}return plan}
export function latestWeeklyPlan(){const row=db().prepare('SELECT id,status,plan_enc,version,updated_at FROM weekly_plans ORDER BY updated_at DESC LIMIT 1').get() as {id:string;status:string;plan_enc:string;version:number;updated_at:string}|undefined;if(!row)return null;return{...decryptSensitive(row.plan_enc),id:row.id,status:row.status,version:row.version,updatedAt:row.updated_at}}
export function listWeeklyPlanSummaries(limit=8){const safeLimit=Math.min(12,Math.max(1,Math.trunc(limit)||8));const rows=db().prepare('SELECT id,status,plan_enc,version,updated_at FROM weekly_plans ORDER BY updated_at DESC LIMIT ?').all(safeLimit) as Array<{id:string;status:string;plan_enc:string;version:number;updated_at:string}>;return rows.map(row=>{const plan=decryptSensitive(row.plan_enc);return{id:row.id,status:row.status,weekStart:plan.weekStart,windowEnd:plan.windowEnd,timezone:plan.timezone,outcomeCount:Array.isArray(plan.outcomes)?plan.outcomes.length:0,blockCount:Array.isArray(plan.blocks)?plan.blocks.length:0,selectedOutcomeCount:Array.isArray(plan.decisions?.selectedOutcomeIds)?plan.decisions.selectedOutcomeIds.length:0,selectedBlockCount:Array.isArray(plan.decisions?.selectedBlockIds)?plan.decisions.selectedBlockIds.length:0,bufferPercent:Number(plan.capacity?.bufferPercent||0),version:row.version,updatedAt:row.updated_at,writesPerformed:false}})}
export function validateWeeklyReview(current:any,input:any){const outcomeIds=new Set(current.outcomes.map((item:any)=>item.id)),blockIds=new Set(current.blocks.map((item:any)=>item.id)),selectedOutcomeIds=(Array.isArray(input.selectedOutcomeIds)?input.selectedOutcomeIds:[]).map(String),selectedBlockIds=(Array.isArray(input.selectedBlockIds)?input.selectedBlockIds:[]).map(String);if(new Set(selectedOutcomeIds).size!==selectedOutcomeIds.length||new Set(selectedBlockIds).size!==selectedBlockIds.length)throw new Error('Doppelte Auswahl-IDs sind nicht erlaubt');if(selectedOutcomeIds.some((value:string)=>!outcomeIds.has(value))||selectedBlockIds.some((value:string)=>!blockIds.has(value)))throw new Error('Auswahl enthält fremde IDs');if(selectedOutcomeIds.length>3||selectedBlockIds.length>3)throw new Error('Maximal drei Ziele und Blöcke auswählen');if(selectedBlockIds.some((value:string)=>!selectedOutcomeIds.includes(current.blocks.find((block:any)=>block.id===value)?.outcomeId)))throw new Error('Ein Block erfordert sein zugehöriges Outcome');if(!selectedOutcomeIds.length)throw new Error('Mindestens ein Wochenziel auswählen');return{selectedOutcomeIds,selectedBlockIds}}
export function reviewWeeklyPlan(id:string,input:any){const row=db().prepare('SELECT id,status,plan_enc,version,updated_at FROM weekly_plans WHERE id=?').get(id) as {id:string;status:string;plan_enc:string;version:number;updated_at:string}|undefined;if(!row)throw new Error('Wochenplan nicht gefunden');const current={...decryptSensitive(row.plan_enc),id:row.id,status:row.status,version:row.version,updatedAt:row.updated_at},{selectedOutcomeIds,selectedBlockIds}=validateWeeklyReview(current,input);const now=new Date().toISOString(),status='reviewed',plan={...current,status,decisions:{selectedOutcomeIds,selectedBlockIds,reviewed:true,reviewedAt:now},updatedAt:now};db().prepare('UPDATE weekly_plans SET status=?,plan_enc=?,version=version+1,updated_at=? WHERE id=?').run(status,encryptSensitive(plan),now,id);db().prepare('INSERT INTO audit_log(id,action,entity_type,entity_id,metadata_json,created_at) VALUES(?,?,?,?,?,?)').run(crypto.randomUUID(),'weekly_plan.review','weekly_plan',id,JSON.stringify({selectedOutcomeCount:selectedOutcomeIds.length,selectedBlockCount:selectedBlockIds.length,writesPerformed:false}),now);return{...plan,version:Number(current.version||1)+1}}
export function listAuditEntries(limit=8){const safeLimit=Math.min(20,Math.max(1,Math.trunc(limit)||8));const rows=db().prepare('SELECT action,entity_type,created_at FROM audit_log ORDER BY created_at DESC LIMIT ?').all(safeLimit) as Array<{action:string;entity_type:string|null;created_at:string}>;return rows.map(row=>({action:row.action,entityType:row.entity_type||'system',createdAt:row.created_at}))}
const preferenceIds=['theme'] as const;export type PreferenceId=typeof preferenceIds[number];
export function isPreferenceId(value:string):value is PreferenceId{return(preferenceIds as readonly string[]).includes(value)}
export function getPreference(id:PreferenceId){const row=db().prepare('SELECT evidence_json,updated_at FROM progress_items WHERE id=?').get(`preference:${id}`) as {evidence_json:string;updated_at:string}|undefined;if(!row)return{id,value:id==='theme'?'dark':null,source:'default',updatedAt:null};const data=JSON.parse(row.evidence_json);return{id,value:data.value,source:'shared-store',updatedAt:row.updated_at}}
export function setPreference(id:PreferenceId,value:unknown){if(id==='theme'&&!['dark','light'].includes(String(value)))throw new Error('Ungültiges Theme');const now=new Date().toISOString(),key=`preference:${id}`,payload=JSON.stringify({value});db().prepare(`INSERT INTO progress_items(id,phase,status,evidence_json,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET evidence_json=excluded.evidence_json,version=progress_items.version+1,updated_at=excluded.updated_at`).run(key,'preferences','active',payload,now);db().prepare('INSERT INTO audit_log(id,action,entity_type,entity_id,metadata_json,created_at) VALUES(?,?,?,?,?,?)').run(crypto.randomUUID(),'preference.update','preference',id,JSON.stringify({source:'agentic-os-ui'}),now);return{id,value,source:'shared-store',updatedAt:now}}
export function backupStore(){db().exec('PRAGMA wal_checkpoint(FULL)');const dir=path.join(stateDir(),'backups');fs.mkdirSync(dir,{recursive:true});const file=path.join(dir,`agentic-os-${new Date().toISOString().replace(/[:.]/g,'-')}.sqlite`);db().exec(`VACUUM INTO '${file.replaceAll("'","''")}'`);return{created:true,fileName:path.basename(file),localOnly:true}}
export function previewRestore(fileName:string){if(path.basename(fileName)!==fileName||!/^agentic-os-[\w-]+\.sqlite$/.test(fileName))throw new Error('Ungültige Backupdatei');const candidate=new DatabaseSync(path.join(stateDir(),'backups',fileName),{readOnly:true});try{const version=(candidate.prepare('SELECT MAX(version) AS version FROM schema_migrations').get() as {version:number|null}).version;return{fileName,schemaVersion:version,status:'review_required',restorePerformed:false}}finally{candidate.close()}}
export function signLocalSession(value:string){const secret=process.env.AUTH_SECRET;if(!secret)throw new Error('AUTH_SECRET fehlt');return`${value}.${crypto.createHmac('sha256',secret).update(value).digest('base64url')}`}
export function verifyLocalSession(value?:string){if(!value)return false;const split=value.lastIndexOf('.');if(split<1)return false;const raw=value.slice(0,split),expected=signLocalSession(raw);return value.length===expected.length&&crypto.timingSafeEqual(Buffer.from(value),Buffer.from(expected))}
export function trustedPrivateHost(host:string){const name=host.split(':')[0].toLowerCase();return name==='localhost'||name==='127.0.0.1'||name.endsWith('.ts.net')||/^10\.|^192\.168\.|^172\.(1[6-9]|2\d|3[01])\./.test(name)}
