import {runtimeSkillDefinitions} from "../skills/registry.ts";
import {getToolDefinition} from "../tools/registry.ts";
import type {RuntimeSource} from "../types.ts";
const sources=new Set<RuntimeSource>(["projects","tasks","inbox","habits","journal_metadata","area_records","weekly_plans"]),planners=new Set(["deterministic-local"]);
const strings=(value:unknown,max=10)=>{if(!Array.isArray(value)||value.length>max)return[];return[...new Set(value.map(String))]};
export function validateCustomAgentConfig(input:Record<string,unknown>){
 const areas=strings(input.areas),providerMode=String(input.providerMode||"none"),model=String(input.model||"none"),status=String(input.status||"metadata_only"),allowedSkills=strings(input.allowedSkills),allowedTools=strings(input.allowedTools),allowedSources=strings(input.allowedSources) as RuntimeSource[],plannerId=String(input.plannerId||"deterministic-local");
 if(areas.some(area=>!["faith","career","health","finance","relations","projects"].includes(area)))throw new Error("Agent enthält einen ungültigen Lebensbereich");if(!["subscription","none"].includes(providerMode)||!["chatgpt-companion-manual","none"].includes(model))throw new Error("Nicht verifizierter Agent Provider");if(providerMode==="subscription"&&model!=="chatgpt-companion-manual")throw new Error("Companion-Modus benötigt die manuelle ChatGPT-Übergabe");if(providerMode==="none"&&model!=="none")throw new Error("Ohne Provider darf kein Modell gewählt sein");if(!["metadata_only","paused"].includes(status))throw new Error("Eigene Agent-Konfiguration ist nicht ausführbar");if(!planners.has(plannerId))throw new Error("Planner ist nicht erlaubt");if(allowedSkills.some(id=>!runtimeSkillDefinitions.some(skill=>skill.id===id)))throw new Error("Skill ist nicht registriert");for(const id of allowedTools)getToolDefinition(id);if(allowedSources.some(source=>!sources.has(source)))throw new Error("Source ist nicht erlaubt");if("customJavaScript" in input||"toolUrl" in input||"modelName" in input)throw new Error("Eigene Code-, URL- oder Modellkonfiguration ist gesperrt");
 return{...input,areas,providerMode,model,status,allowedSkills,allowedTools,allowedSources,plannerId};
}
