"use client";
import { useCallback, useEffect, useState } from "react";
import { Brain, Check, RefreshCw, ShieldAlert, X } from "lucide-react";
import { privateApiFetch } from "@/lib/private-client";

export function MemoryReview({ notify }: { notify: (message: string) => void }) {
  const [state,setState]=useState<"loading"|"online"|"error">("loading"),[items,setItems]=useState<any[]>([]),[busy,setBusy]=useState(""),[confirmPolicy,setConfirmPolicy]=useState("");
  const load=useCallback(async()=>{setState("loading");setItems([]);try{const response=await privateApiFetch("/api/agents/memory",{cache:"no-store"}),body=await response.json();if(!response.ok||!body.inventoryVerified)throw new Error();setItems(body.memories||[]);setState("online")}catch{setState("error");setItems([])}},[]);
  useEffect(()=>{load()},[load]);
  const decide=async(item:any,action:"activate"|"reject"|"supersede")=>{if(item.kind==="policy"&&action==="activate"&&confirmPolicy!==item.id){setConfirmPolicy(item.id);return}setBusy(item.id);try{const response=await privateApiFetch("/api/agents/memory",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:item.id,version:item.version,action})}),body=await response.json();if(response.status===409){await load();throw new Error("Memory wurde inzwischen geändert; aktueller Stand wurde geladen")}if(!response.ok)throw new Error(body.error||"Memory-Entscheidung abgelehnt");await load();setConfirmPolicy("");notify(action==="activate"?"Memory aktiviert":action==="reject"?"Memory abgelehnt":"Memory superseded")}catch(error){notify(error instanceof Error?error.message:"Memory-Quelle nicht erreichbar")}finally{setBusy("")}};
  return <section className="memoryReview" aria-labelledby="memory-review-title"><div className="sectionhead"><div><h3 id="memory-review-title">Memory Review</h3><span>Strukturierte Erinnerungen mit Herkunft und Nutzerentscheidung</span></div><button onClick={load} disabled={state==="loading"} aria-label="Memory neu laden"><RefreshCw/></button></div>{state==="loading"&&<p role="status">Memory Store wird geprüft …</p>}{state==="error"&&<div className="honestEmpty"><Brain/><span><b>Memory Store nicht erreichbar</b>Keine alten Kandidaten werden als aktuell angezeigt.</span><button onClick={load}>Erneut prüfen</button></div>}{state==="online"&&items.length===0&&<div className="honestEmpty"><Brain/><span><b>Keine offenen oder aktiven Memories</b>Normale Agentenläufe erzeugen keine automatischen Kandidaten.</span></div>}{state==="online"&&<div className="memoryReviewList">{items.map(item=><article key={item.id} className={item.kind==="policy"?"policyMemory":""}><div className="row"><b>{item.kind} · {item.scope}{item.scopeId?` / ${item.scopeId}`:""}</b><em>{item.status}</em></div><p>{String(item.content).slice(0,240)}{String(item.content).length>240?"…":""}</p><small>Quelle: {item.sourceType}{item.sourceId?` · ${item.sourceId}`:""} · {new Intl.DateTimeFormat("de-DE",{dateStyle:"medium",timeStyle:"short",timeZone:"Europe/Berlin"}).format(new Date(item.createdAt))}{item.confidence!=null?` · Konfidenz ${Math.round(item.confidence*100)} %`:""}</small>{item.kind==="policy"&&<p className="workflowBoundary"><ShieldAlert/>Policy Memory verändert verbindlichen Kontext und benötigt eine zweite ausdrückliche Bestätigung.</p>}<div className="editorActions">{item.status==="candidate"&&<><button disabled={busy===item.id} onClick={()=>decide(item,"reject")}><X/>Ablehnen</button><button disabled={busy===item.id} onClick={()=>decide(item,"activate")}><Check/>{item.kind==="policy"&&confirmPolicy===item.id?"Policy wirklich aktivieren":"Aktivieren"}</button></>}{item.status==="active"&&<button disabled={busy===item.id} onClick={()=>decide(item,"supersede")}>Supersede</button>}</div></article>)}</div>}</section>;
}
